### ISSUE TITLE
[Question] Examples

### ISSUE THREAD

**Issue by aleksander-trepala** [BAndysc/nodify-avalonia#21]
Hi! I've started creating a new project out of Playground example. 
I downloaded the latest release repository, but instead of using the basic Nodify project from that, I moved Nodify.Playground and Nodify.Shared into my repository.
After that I've downlaoded NodifyAvalonia via NuGet.
Issue is that after I rename the Playground project, it no longer builds:
- Method StartLoopingAnimation is unavailable (it's in internal extensions class).
- In AssemblyInfo.cs ResourceDictionaryLocation is also not available.
Is there any way around this? Should I approach my project creation differently?

**Comment by BAndysc** [comment]
> Method StartLoopingAnimation is unavailable (it's in internal extensions class).

This method is also internal in upstream https://github.com/miroiu/nodify/blob/1425d404a80a54985c4b96a6c1003b39c5e6c8c6/Nodify/Helpers/DependencyObjectExtensions.cs#L11

and it is ultimately a wrapper utility over some WPF/Avalonia methods, definitely not part of Nodify API (neither WPF nor Avalonia), so if you want to use it, just copy-paste this extension method to your project.

> In AssemblyInfo.cs ResourceDictionaryLocation is also not available.

You can remove it, this is an empty class/enum/attribute in Avalonia. In WPF is it required for styling, but in Avalonia ResourceDictionary needs to be attached manually in App.axaml or other xaml file. I specifically do not remove these WPF-only things so that there is as few merge conflicts as possible. But it serves no other purpose.

Let me know if you have other questions!

**Comment by BAndysc** [comment]
Closing the issue, hopefully I've answered your questions.
